(defun c:arr (/ dimbk dimsz pt0 pt1 arr_ent)
	(setq pt0 (getpoint "\n起点："))
	(if pt0 (setq pt1 (getpoint pt0 "\n下一点：")))
	(if pt1
		(setq arr_ent (list	'(0 . "LEADER")
			(cons 3 (strcat (getvar "dimstyle") "$7"))
			(cons 8 FLLT_DIM0)
			'(71 . 1)
			'(72 . 0)
			'(73 . 3)
			'(74 . 1)
			'(75 . 0)
			'(100 . "AcDbEntity")
			'(100 . "AcDbLeader")
			(cons 10 pt0)
			(cons 10 pt1)
		))
	)
	(if arr_ent
		(progn
			(entmake arr_ent)
			(setq arr_ent (entget (entlast)))
		)
		(setq pt1 nil)
	)
	(while pt1
		(setq arr_ent (append arr_ent (list (cons 10 pt1))))
		(entmod arr_ent)
		(setq pt1 (getpoint pt1 "\n下一点："))
	)
	(princ)
)

(princ "FishLISP C:ARR ")
(princ)
