; 2000-06-05调用新的Sort函数；
; 增加错误自陷；
; 改进界面。

(setq olderr *error*)
(defun *error* (s)
	(setq *error* olderr olderr nil)
	(princ "Loading ABORT! \nA required FUNCTION.LSP not found in search path. ")
	(princ)
)

(if (findfile "function.lsp")
	(load "function")
	(exit)
)

(setq *error* olderr olderr nil)

(defun c:dimlin2 (/ );ss amnt pt_base pt_ext olderr)
	;(fishlisp "DIMLIN" "v2.0")
	;(fl_undo_begin)
	;(setq olderr *error*)
	;(defun *error* (s)
	;(if _csset (csrestore))
	;(if oo (setvar "orthomode" oo oo nil))
	;(if os (setvar "osmode" os os nil))
	;(if cl (setvar "clayer" cl cl nil))
	;(if ucsf (setvar "ucsfollow" ucsf ucsf nil))
	;(setq *error* (if olderr olderr *pub_err*))
	;(setvar "ucsicon" 1)
	;(setvar "blipmode" 1)
	;(fl_undo_end)
	;(princ)
	;)
	(cssave)
	(prompt "\nSelect lines to dim: ")
	(setq ss (ssget '((0 . "line"))))
	(if ss (setq amnt (sslength ss)))
	(if (> amnt 1) (setq pt_base (getpoint "\n标注点：")))
	(if pt_base (dimlin))
	(csrestore)
	(setq *error* olderr olderr nil)
;(fl_undo_end)
	(princ)
)

(defun dimlin (/ ); ent pt1 pt2 ang y_list idx oo os cl ucsf)
	(setq 
		oo (getvar "orthomode")
		os (getvar "osmode")
		cl (getvar "clayer")
		ucsf (getvar "ucsfollow")
		dims (getvar "dimscale")
	)
	;(setvar "cmdecho" 0)
	(setvar "blipmode" 0)
	(setvar "orthomode" 0)
	(setvar "osmode" 0)
	(setvar "ucsfollow" 0)
	(setvar "ucsicon" 0)
	(cmd "_layer" "m" "标注 0" "c" "g" "" "")
	(setq 
		ent (entget (ssname ss 0))
		pt1 (cdr (assoc 10 ent))
		pt2 (cdr (assoc 11 ent))
		ang (/ (* (angle pt1 pt2) 180.0) pi)
	)
	(if (and (> ang 45.0) (< ang 225.0)) (setq pttemp pt1 pt1 pt2 pt2 pttemp pttemp nil ang (rem (+ ang 180.0) 360.0)))
	(cmd "_ucs" "z" ang)
	(setq y_list (list) idx 0)
	(setq x_00 (car (trans pt_base 0 1)))
	(if (>= (abs (- (car (trans pt1 0 1)) x_00)) (abs (- (car (trans pt2 0 1)) x_00)))
		(setq 
			x_01 (+ x_00 (* 10.0 dims))
			x_02 (+ x_00 (* 20.0 dims))
		)
		(setq 
			x_01 (- x_00 (* 10.0 dims))
			x_02 (- x_00 (* 20.0 dims))
		)
	)
	(repeat amnt
		(setq y_list (append y_list (list (cadr (trans (cdr (assoc 10 (entget (ssname ss idx)))) 0 1)))))
		(setq idx (1+ idx))
	)
	(setq 
		y_list (vl-sort y_list '<) 
		idx 0
		y_00 (nth 0 y_list)
		pt01 (list x_00 y_00)
	)
	(repeat (1- amnt)
		(setq 
			pt1 (list x_00 (nth idx y_list))
			pt2 (list x_00 (nth (setq idx (1+ idx)) y_list))
		)
		(cmd "_dim1" "ver" pt1 pt2 (list x_01 y_00) "")
	)
	(setq pt02 pt2)
	(cmd "_dim1" "ver" pt01 pt02 (list x_02 y_00) "")

	(setvar "cmdecho" 1)
	(setvar "orthomode" oo)
	(setvar "osmode" os)
	(setvar "clayer" cl)
	(setvar "blipmode" 1)
	(setvar "ucsfollow" ucsf)
	(setvar "ucsicon" 1)
)

(defun c:dl () (c:dimlin2) (princ))

(princ "\loaded. Start as C:DIMLIN or C:DL")
(princ)
