(defun c:drwv (/ os pw flg loop pt0 pt1 pt2 pt3 pt4 vnm spc hei wid k)
	(defun *error* (s)
		(setvar "cmdecho" 0)
		(if os (setvar "osmode" os))
		(if pw (setvar "plinewid" pw))
		(fl_undo_end)
		(setq *error* olderr)
		(princ)
	)
	(setvar "cmdecho" 0)
	(fl_undo_begin)
	(setq os (getvar "osmode"))
	(setq pw (getvar "plinewid"))
	(setvar "osmode" 0)
	(setvar "plinewid" 0.0)
	
	(if drwv_k nil (setq drwv_k "Pline"))
	(initget "Pline Vector")
	(princ (strcat "\nDraw in [Pline/Vector]: <" drwv_k "> "))
	(setq k (getkword))
	(setq k (if k k drwv_k))
	(setq drwv_k k)

	(setq flg t loop t)
	(while (and loop (setq vw (tblnext "view" flg)))
		(setq 
			pt0 (cdr (assoc 10 vw))
			;pt0 (trans pt0 1 0)
			vnm (cdr (assoc 2 vw))
			spc (cdr (assoc 70 vw))
			ang 0;(- 0 (cdr (assoc 50 vw)))
			hei (/ (cdr (assoc 40 vw)) 2.0)
			wid (/ (cdr (assoc 41 vw)) 2.0)
			pt1 (polar (polar pt0 (+ (/ pi -2) ang) hei) (+ pi ang) wid)
			pt2 (polar (polar pt0 (+ (/ pi -2) ang) hei) (+ 0 ang) wid)
			pt3 (polar (polar pt0 (+ (/ pi 2) ang) hei) (+ 0 ang) wid)
			pt4 (polar (polar pt0 (+ (/ pi 2) ang) hei) (+ pi ang) wid)
		)
		(if (= k "Vector")
			(grvecs (list 1 pt1 pt2 1 pt2 pt3 1 pt3 pt4 1 pt4 pt1 1 pt1 pt3 1 pt2 pt4))
			(cmd "pline" pt1 pt2 pt3 pt4 "c")
		)
		(setq flg nil)
	)
	(setvar "osmode" os)
	(setvar "plinewid" pw)
	(fl_undo_end)
	(setvar "cmdecho" 1)
	(princ)
)

(princ "loaded. Start as C:DRWV ")
(princ)