(defun c:fractal (/ en)
	(if (setq en (entsel "\nSelect a LINE object: "))
		(progn
			(initget "1 2 3 4")
			(setq key (getkword "\nSelect method: [1/2/3/4] "))
			(setq fac 0.618)
			(cond
				((= key "1")
					(mapcar 'frc1 (list (car en)))
				)
				((= key "2")
					(mapcar 'frc2 (list (car en)))
				)
				((= key "3")
					(mapcar 'frc3 (list (car en)))
				)
				((= key "4")
					(mapcar 'frc4 (list (car en)))
				)
			);cond
		);progn
);if
(princ)
);defun

(defun frc1 (line_en)
	(setq 
		ent (entget line_en)
		pt1 (cdr (assoc 10 ent))
		pt2 (cdr (assoc 11 ent))
		an1 (angle pt1 pt2)
		an2 (+ an1 (/ pi 2.0))
		dis (/ (distance pt1 pt2) 2.0)
		fac (* fac 1)
		pt3 (polar pt1 an1 dis)
		pt4 (polar pt3 an2 (* dis fac))
		en1 (entmake (list '(0 . "line") (cons 10 pt1) (cons 11 pt4)))
		en1 (entlast)
		en2 (entmake (list '(0 . "line") (cons 10 pt4) (cons 11 pt2)))
		en2 (entlast)
	);setq
	(entdel line_en)
	(redraw)
	(if (> dis 1)
		(mapcar 'frc1 (list en1 en2))
	)
	(princ)
);defun

(defun frc2 (line_en)
	(setq 
		ent (entget line_en)
		pt1 (cdr (assoc 10 ent))
		pt2 (cdr (assoc 11 ent))
		an1 (angle pt1 pt2)
		an2 (+ an1 (/ pi 2.0))
		dis (distance pt1 pt2)
		pt3 (polar pt1 an1 (/ dis 3.0))
		pt4 (polar pt1 an1 (* dis (/ 2.0 3.0)))
		pt5 (polar pt3 an2 (/ dis 3.0))
		pt6 (polar pt4 an2 (/ dis 3.0))
		en1 (entmake (list '(0 . "line") (cons 10 pt1) (cons 11 pt5)))
		en1 (entlast)
		en2 (entmake (list '(0 . "line") (cons 10 pt5) (cons 11 pt6)))
		en2 (entlast)
		en3 (entmake (list '(0 . "line") (cons 10 pt6) (cons 11 pt2)))
		en3 (entlast)
	);setq
	(entdel line_en)
	(redraw)
	(if (> dis 1)
		(mapcar 'frc2 (list en1 en2 en3))
	)
	(princ)
);defun

(defun frc3 (line_en)
	(setq 
		ent (entget line_en)
		pt1 (cdr (assoc 10 ent))
		pt2 (cdr (assoc 11 ent))
		an1 (angle pt1 pt2)
		an2 (+ an1 (/ pi 2.0))
		dis (distance pt1 pt2)
		pt3 (polar pt1 an1 (/ dis 3.0))
		pt4 (polar pt1 an1 (* dis (/ 2.0 3.0)))
		pt5 (polar pt3 an2 (/ dis 2.8))
		pt6 (polar pt4 an2 (/ dis -3.5))
		en1 (entmake (list '(0 . "line") (cons 10 pt1) (cons 11 pt5)))
		en1 (entlast)
		en2 (entmake (list '(0 . "line") (cons 10 pt5) (cons 11 pt6)))
		en2 (entlast)
		en3 (entmake (list '(0 . "line") (cons 10 pt6) (cons 11 pt2)))
		en3 (entlast)
	);setq
	(entdel line_en)
	(redraw)
	(if (> dis 1)
		(mapcar 'frc3 (list en1 en2 en3))
	)
	(princ)
);defun

(defun frc4 (line_en)
	(setq 
		ent (entget line_en)
		pt1 (cdr (assoc 10 ent))
		pt2 (cdr (assoc 11 ent))
		an1 (angle pt1 pt2)
		an2 (+ an1 (/ pi 2.0))
		dis (distance pt1 pt2)
		pt3 (polar pt1 an1 (/ dis 2.0))
		pt4 (polar pt1 an1 (/ dis 3.0))
		pt5 (polar pt1 an1 (* dis (/ 2.0 3.0)))
		pt6 (polar pt3 an2 (* dis 0.288))
		en1 (entmake (list '(0 . "line") (cons 10 pt1) (cons 11 pt4)))
		en1 (entlast)
		en2 (entmake (list '(0 . "line") (cons 10 pt4) (cons 11 pt6)))
		en2 (entlast)
		en3 (entmake (list '(0 . "line") (cons 10 pt6) (cons 11 pt5)))
		en3 (entlast)
		en4 (entmake (list '(0 . "line") (cons 10 pt5) (cons 11 pt2)))
		en4 (entlast)
	);setq
	(entdel line_en)
	(redraw)
	(if (> dis 1)
		(mapcar 'frc4 (list en1 en2 en3 en4))
	)
	(princ)
);defun

(princ "loaded. Start as C:FRACTAL ")
(princ)