(defun c:mo (/ olderr os dist dis dis0 ens pt ent pt1 amt)
	(prompt "\nMultiple Offset, FishLISP, May 13 1996")
	(setq olderr *error*)
	(defun *error* (s)
		(if os (setvar "osmode" os))
		(setvar "cmdecho" 0)
		(fl_undo_end)
		(setvar "cmdecho" 1)
		(setq *error* olderr)
		(princ)
	)
	(setvar "cmdecho" 0)
	(fl_undo_begin)
	(setq os (getvar "osmode"))
	(setvar "osmode" 0)
	(setq dist (getvar "offsetdist"))
	(princ "\nOffset distance <")
	(princ (if (minusp dist) 0.0 dist))
	(setq dis (getdist ">:"))
	(if (= dis nil) (setq dis dist))
	(setq dis0 dis)
	(setq amt (getint "\nHow many time to offset, or RETURN to apply a distance:"))
	(if amt nil
		(setq amt (fix (/ (getdist "\nFirst point:") dis0)))
	) 
	(while (setq ens (entsel))
		(setq 
			pt (cadr ens)
			ent (car ens)
			pt1 (getpoint "\nWhich side :")
		)
		(repeat amt 
			(cmd "_offset" dis pt pt1 "")
			(setq dis (+ dis dis0))
		)
		(setq dis dis0)
	)
	(setvar "offsetdist" dis0)
	(setvar "osmode" os)
	(fl_undo_end)
	(setvar "cmdecho" 1) 
	(princ) 
)

