; 2025-11-21		rewriting
; 2001-07-25 v1.1	修正了一个在AutoCAD2000中的一个字符大小写敏感问题
; 1998-07-16 v1.0	改变门的尺寸

(setq dr_list (list))
(foreach itm (list "DR1" "DR2" "DR3" "DR4" "DR5" "DR6" "DR7" "DR8")
	(if (findfile (strcat itm ".DWG"))
		nil 
		(setq dr_list (append dr_list (list itm))))
)
(if dr_list
	(progn
		(princ (strcat "\n" (fl_strlist_2_string dr_list ".dwg, ") "not found. Application abort! "))
		(exit)
	)
)

(defun mod_line (flag_ pt_ dist_ / ss_pt idx new_pt ent1)
	(cmd "select" ss0 "")
	(setq ss_pt (ssget "p" (list (cons flag_ pt_))))
	(if ss_pt
		(progn
			(setq idx 0)
			(setq new_pt (polar pt_ bkang dist_))
			(repeat (sslength ss_pt)
			(setq ent1 (entget (ssname ss_pt idx)))
			(entmod (subst (cons flag_ new_pt) (assoc flag_ ent1) ent1))
			(setq idx (1+ idx))
			)
		)
	)
)

(defun check_dr (drname_)
	(if (tblsearch "block" drname_)
		nil
		(progn
			(cmd "insert" drname_ "0,0" "1" "1" "0")
			(entdel (entlast))
		)
	)
)

(defun resize_dr (en_ / ent bkname bkins bksc bkang new_sc f_pt1 f_pt2 ss_cap cap1 cap2 pt1 pt2 pt3 pt4 dst ss0 en_kpt)
	(setvar "cmdecho" 0)
	(cmd "_undo" "_mark")
	(setq 
		ent 	(entget en_)
		bkname 	(strcase (cdr (assoc 2 ent)))
		bkins	(cdr (assoc 10 ent))
		bksc	(abs (cdr (assoc 41 ent)))
		old_sc	(* 1000 bksc)
		bkang	(cdr (assoc 50 ent))
	) 
	(setq new_sc (getint (strcat "\nWidth: <" (rtos old_sc 2 0) "> ")))
	(if (and new_sc (/= new_sc old_sc))
		(progn
			(setq new_sc (/ new_sc 1000.0))
			(cond 
				((= bkname "DR1")
					(cond 
						((<= new_sc 1.0)
							(entmake (subst (cons 2 "DR3") (assoc 2 ent) ent))
							(entmod (subst (cons 2 "DR4") (assoc 2 ent) ent))
							(setq en_kpt (entsel "\n>>Door to be kept: "))
							(if en_kpt
								(progn
									(setq en_kpt (car en_kpt))
									(cmd "erase" en_ (entlast) "r" en_kpt "")
								)
							)
						)
						((>= new_sc 3.0)
							(entmod (subst (cons 2 "DR7") (assoc 2 ent) ent))
						)
					)
				)
				((= bkname "DR2")
					(cond 
						((<= new_sc 1.0)
							(entmake (subst (cons 2 "DR5") (assoc 2 ent) ent))
							(entmod (subst (cons 2 "DR6") (assoc 2 ent) ent))
							(setq en_kpt (entsel "\n>>Door to be kept: "))
							(if en_kpt
								(progn
									(setq en_kpt (car en_kpt))
									(cmd "erase" en_ (entlast) "r" en_kpt "")
								)
							)
						)
						((>= new_sc 3.0)
							(entmod (subst (cons 2 "DR8") (assoc 2 ent) ent))
						)
					)
				)
				((member bkname (list "DR3" "DR4"))
					(cond
						((> 3.0 new_sc 1.0)
							(entmod (subst (cons 2 "DR1") (assoc 2 ent) ent))
						)
						((>= new_sc 3.0)
							(entmod (subst (cons 2 "DR7") (assoc 2 ent) ent))
						)
					)
				)
				((member bkname (list "DR5" "DR6"))
					(cond
						((> 3.0 new_sc 1.0)
							(entmod (subst (cons 2 "DR2") (assoc 2 ent) ent))
						)
						((>= new_sc 3.0)
							(entmod (subst (cons 2 "DR8") (assoc 2 ent) ent))
						)
					)
				)
				((= bkname "DR7")
					(cond 
						((<= new_sc 1.0)
							(entmake (subst (cons 2 "DR3") (assoc 2 ent) ent))
							(entmod (subst (cons 2 "DR4") (assoc 2 ent) ent))
							(setq en_kpt (entsel "\n>>Door to be kept: "))
							(if en_kpt
								(progn
									(setq en_kpt (car en_kpt))
									(cmd "erase" en_ (entlast) "r" en_kpt "")
								)
							)
						)
						((> 3.0 new_sc 1.0)
							(entmod (subst (cons 2 "DR1") (assoc 2 ent) ent))
						)
					)
				)
				((= bkname "DR8")
					(cond 
						((<= new_sc 1.0)
							(entmake (subst (cons 2 "DR5") (assoc 2 ent) ent))
							(entmod (subst (cons 2 "DR6") (assoc 2 ent) ent))
							(setq en_kpt (entsel "\n>>Door to be kept: "))
							(if en_kpt
								(progn
									(setq en_kpt (car en_kpt))
									(cmd "erase" en_ (entlast) "r" en_kpt "")
								)
							)
						)
						((> 3.0 new_sc 1.0)
							(entmod (subst (cons 2 "DR2") (assoc 2 ent) ent))
						)
					)
				)
			)
			(cmd "scale" (if en_kpt en_kpt en_) "" bkins "r" bksc new_sc)
			(setq en_kpt nil)
			(setq 
				f_pt1 (polar bkins bkang (+ (* bksc 500) 50))
				f_pt2 (polar bkins bkang (- (+ (* bksc 500) 50)))
				ss_cap (ssget "f" (list f_pt1 f_pt2))
				ss_cap (ssget "p" (list (cons 8 FLLT_WALL) '(0 . "LINE")))
				cap1 (entget (ssname ss_cap 0))
				cap2 (entget (ssname ss_cap 1))
				pt1 (cdr (assoc 10 cap1))
				pt2 (cdr (assoc 11 cap1))
				pt3 (cdr (assoc 10 cap2))
				pt4 (cdr (assoc 11 cap2))
				dst (/ (- new_sc bksc) 0.002)
				ss0 (ssget "cp" (list pt1 pt2 pt4 pt3))
				ss0 (ssget "p" (list '(0 . "LINE") (cons 8 FLLT_WALL)))
			)
			(mod_line 10 pt1 dst)
			(mod_line 11 pt1 dst)
			(mod_line 10 pt2 dst)
			(mod_line 11 pt2 dst)
			(mod_line 10 pt3 (- dst))
			(mod_line 11 pt3 (- dst))
			(mod_line 10 pt4 (- dst))
			(mod_line 11 pt4 (- dst))
		)
	)
)

(defun c:rsdr (/ olderr ucsf os undo_id en loop)
	(princ "\nResize Doors.")
	(setvar "cmdecho" 0)
	(mapcar 'check_dr (list "DR1" "DR2" "DR3" "DR4" "DR5" "DR6" "DR7" "DR8"))
	(setvar "cmdecho" 0)
	(setq ucsf (getvar "ucsfollow"))
	(setvar "ucsfollow" 0)
	(setvar "expert" 4)
	(setvar "cmdecho" 0)
	(cmd "ucs" "s""$temp$")
	(cmd "ucs" "w")

	(setq os (getvar "osmode"))
	(setvar "osmode" 0)
	(setvar "cmdecho" 0)
	(setq undo_id 0)
	(setq loop t)
	(while loop
		(if (< undo_id 1)
			(setq en (entsel "\nPick a DR insert: "))
			(progn
				(initget "Undo")
				(setq en (entsel "\n[Undo]<Pick a Door>: "))
			)
		)
		(setq enn (car en)
			ent (entget enn)
		)
		(cond
			((not en)
				(setq loop nil)
			)
			((= en "Undo")
				(cmd "undo" "")
				(setq undo_id (1- undo_id))
			)
			((/= (cdr (assoc 0 ent)) "INSERT")
				(princ "\n1 was not an Insert. ")
			)
			((/= (strcase (substr (cdr (assoc 2 ent)) 1 2)) "DR")
				(princ "\n1 was not DR insert. ")
			)
			(t
				(resize_dr enn)
				(setq undo_id (1+ undo_id))
			)
		)
	)
	(setvar "cmdecho" 0)
	(cmd "ucs" "r" "$temp$")
	(cmd "ucs" "d" "$temp$")
	(setvar "ucsfollow" ucsf)
	(setvar "expert" 0)
	(setvar "osmode" os)
	(setvar "cmdecho" 1)
	(princ)
)

(princ "loaded. Start as C:RSDR. ")
(princ)