
(defun c:rta (/ ang pt ss p0 en)
	(setq rta_ang (if rta_ang rta_ang 0))
	(princ "\nAngle: <")
	(princ rta_ang)
	(princ "> ")
	(setq ang (getangle))
	(setq ang (if ang (/ (* 180 ang) pi)))
	(setq ang (if ang ang rta_ang))
	(setq rta_ang ang)
	(setq ang (- ang))
	(initget "Object")
	(while (setq pt (getpoint "\nSpecify base point[Object base]: "))
		(cond
			((= pt "Object")
				(setq ss (ssget) idx 0)
				(repeat (sslength ss)
				(setq 
					en (ssname ss idx)
					p0 (cdr (assoc 10 (entget en)))
				)
				(setvar "cmdecho" 0)
				(if ss (cmd "rotate" en "" p0 ang))
					(setvar "cmdecho" 1)
					(setq idx (1+ idx))
				)
			)
			((listp pt)
				(setq ss (ssget))
				(setvar "cmdecho" 0)
				(if ss (cmd "rotate" ss "" pt ang))
				(setvar "cmdecho" 1)
			)
		)
		(initget "Object")
	)
	(princ)
)

(princ "loaded. C:RTA ")
(princ)

