(defun c:scel (/ dims el_ss el_amt idx el_ent osm ins_pt ins_sc)
	(prompt "\nFishLISP. 5-28-1998. ")
	(prompt "\nRescale elevation blocks. ")
	(setq olderr *error*)
	(defun *error* (s)
		(csrestore)
		(fl_undo_end)
		(setq *error* olderr olderr nil)
		(princ)
	)
	(fl_undo_begin)
	(princ (strcat "\nDimscale: <" (rtos (getvar "dimscale")) "> "))
	(initget 6)
	(setq dims (getreal))
	(if dims nil (setq dims (getvar "dimscale")))
	(setq el_ss (ssget '((0 . "insert")(2 . "el??,EL??,sy1,sy2,sy3,sy4,dim_bg,dim_rl,zbr,zbl,al,ar"))))
	(setq 
		el_amt (if el_ss (sslength el_ss) 0)
		idx 0
		osm (getvar "osmode")
	)
	(cssave)
	(setvar "cmdecho" 0)
	(setvar "osmode" 0)
	(repeat el_amt
		(setq 
			el_en (ssname el_ss idx)
			el_ent (entget el_en)
			ins_pt (cdr (assoc 10 el_ent))
			ins_sc (abs (cdr (assoc 41 el_ent)))
		)
		(if (= ins_sc dims) nil (cmd "scale" el_en "" ins_pt "r" ins_sc dims))
		(setq idx (1+ idx))
	)
	(csrestore)
	(redraw)
	(fl_undo_end)
	(setvar "osmode" osm)
	(setvar "cmdecho" 1)
	(setq *error* olderr)
	(princ)
)

(princ "loaded. Start as C:SCEL. ")
(princ)